const wcProjects = [
  {
        "title": "Hewett Bayou Connector (E Lamb Drive Extension)",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "This project is for the construction of a new two (2) lane roadway from East Lamb Drive to East Hewett Rd. Scope of work includes the construction of an approximate 325 ft concrete bridge over Hewett Bayou, attached 6 ft sidewalk and associated drainage features. Roadway segment is one (1) mile...",
        "budget": "$4.6M",
        "funding": "Capital Projects Fund",
        "district": "District 4",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "CR 280 Bob Sikes Roadway Resurfacing Project Phase I",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "This project scope is for Phase 1 construction of CR 280 Bob Sikes from US 331 to 900 ft west of Pleasant Ridge Rd. Scope of work includes operational improvements such as turn lanes additions and/or expansion near the the US 331 intersection, milling and resurfacing, associated drainage...",
        "budget": "$4.2M",
        "funding": "Grant Funded- SCOP",
        "district": "District 3",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "Blue Gulf Resort Roadway & Drainage Improvements",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "Blue Gulf Resort Roadway & Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2.5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Poinicana Blvd Roadway, Drainage & Pedestrian Improvements",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "Poinicana Blvd Roadway, Drainage & Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.8M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Fox Lake Drainage Improvements",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "Fox Lake Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$912K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Poinciana Blvd & Scenic Hwy 98 Intersection Signalization",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "The intersection signalization of Poinciana Blvd and Scenic Hwy 98 (CR 2378) has been designed. Previously, it was included as part of the Poinciana Blvd Roadway and Drainage Improvements project but recently was determined to separate it in order to expedite the signalization component....",
        "budget": "$900K",
        "funding": "Capital Projects Fund",
        "district": "District 4",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "Madge Lane & Sally Lane Roadway & Drainage Improvements",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "This project includes asphalt paving of existing dirt roads and includes stormwater drainage improvements within existing limited rights-of-way. No pedestrian features are included with these projects due to the constrained rights-of-way.",
        "budget": "$536K",
        "funding": "Public Works Capital Fund",
        "district": "District 4",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "Holiday Shores Drainage & Pedestrian Improvements Phase III",
        "dept": "Public Works",
        "category": "drainage",
        "category_label": "Drainage",
        "description": "Holiday Shores Drainage & Pedestrian Improvements Phase III is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$125K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Tourism Visitor and Discovery Center",
        "dept": "Tourism",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Tourism Visitor and Discovery Center is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$9.5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "CR 83 N (Blue Mountain Rd) Extension from US 98 to Chat Holley",
        "dept": "Public Works",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "CR 83 N (Blue Mountain Rd) Extension from US 98 to Chat Holley is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$8.7M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027–FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Baldwin Library/Learning Center",
        "dept": "BCC",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Baldwin Library/Learning Center is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$8M",
        "funding": "Capital Projects Fund",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Rock Hill Rd Improvements- Phase 4 (Final)",
        "dept": "Public Works",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Rock Hill Rd Improvements- Phase 4 (Final) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6.2M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Building Construction & Maintenance Facility",
        "dept": "BCC",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Building Construction & Maintenance Facility is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$3.5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Rock Hill Rd Improvements - Phase 3",
        "dept": "Public Works",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Rock Hill Rd Improvements - Phase 3 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$3.2M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Coastal Branch Library Expansion",
        "dept": "BCC",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Coastal Branch Library Expansion is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$3M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Rock Hill Rd Improvements - Phase 2",
        "dept": "Public Works",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Rock Hill Rd Improvements - Phase 2 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2.3M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Morrison Springs Site Improvements (Boat Launch Facility)",
        "dept": "Public Works",
        "category": "facilities",
        "category_label": "Facilities",
        "description": "Morrison Springs Site Improvements (Boat Launch Facility) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$500K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Alderberry Connector Road Extension",
        "dept": "Public Works",
        "category": "parks",
        "category_label": "Parks",
        "description": "This project proposes a new two (2) lane roadway from East Hewett Rd to Don Bishop Rd (via Mario Rd). Project intent it to include Complete Street elements, such as paths, sidewalks, trail or bike lanes. This project is part of a phased approach to create an alternative roadway connection to US...",
        "budget": "$8.5M",
        "funding": "Capital Projects Fund",
        "district": "District 4",
        "target": "FY2027–FY2031",
        "status_text": "Design Phase",
        "status_class": "wc-status-design"
    },
    {
        "title": "Holiday Shores Drainage & Pedestrian Improvements Phase II",
        "dept": "Public Works",
        "category": "parks",
        "category_label": "Parks",
        "description": "The proposed project phase includes the construction of drainage improvements and pedestrian facilities in the Holiday Shores neighborhood area. Phase 2 project limits are Holiday Rd from US Hwy 98 to Forest Shore Drive and east along Forest Shore Drive to Paradise Park.",
        "budget": "$7.6M",
        "funding": "Capital Projects Fund",
        "district": "District 4",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "Miramar Beach Parking Facility",
        "dept": "Tourism",
        "category": "parks",
        "category_label": "Parks",
        "description": "Miramar Beach Parking Facility is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6.5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Santa Rosa Beach Performing Arts Park",
        "dept": "Tourism",
        "category": "parks",
        "category_label": "Parks",
        "description": "Santa Rosa Beach Performing Arts Park is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6.5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Sugar Drive Connector Rd",
        "dept": "Public Works",
        "category": "parks",
        "category_label": "Parks",
        "description": "This project proposes a new two (2) lane roadway from Sugar Drive to Thompson Rd. Project intent it to include Complete Street elements, such as paths, sidewalks, trail or bike lanes.",
        "budget": "$3.4M",
        "funding": "Capital Projects Fund",
        "district": "District 4",
        "target": "FY2027–FY2030",
        "status_text": "Design Phase",
        "status_class": "wc-status-design"
    },
    {
        "title": "CR 30A & S Watersound Parkway Signalized Intersection",
        "dept": "Public Works",
        "category": "parks",
        "category_label": "Parks",
        "description": "CR 30A & S Watersound Parkway Signalized Intersection is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2.5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Walton Dunes Beach Access",
        "dept": "Tourism",
        "category": "parks",
        "category_label": "Parks",
        "description": "Walton Dunes Beach Access is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2.1M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Walton Magnolia and Park Place Drainage Improvements",
        "dept": "Public Works",
        "category": "parks",
        "category_label": "Parks",
        "description": "Walton Magnolia and Park Place Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$426K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "South Orange Street Pedestrian Improvements",
        "dept": "Public Works",
        "category": "parks",
        "category_label": "Parks",
        "description": "This project includes the construction of a sidewalk along South Orange Street from US Hwy 98 to Inlet Beach Regional Access Park.",
        "budget": "$243K",
        "funding": "Capital Projects Fund",
        "district": "District 5",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "Radio Project",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Radio Project is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$10.1M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Freeport 3280/Bearcreek Fire Station",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Freeport 3280/Bearcreek Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$7M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027–FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pleasant Ridge Fire Station",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Pleasant Ridge Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$7M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027–FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Fire Station",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6.6M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Hammock Bay Fire Station",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Hammock Bay Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6.6M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Fleet Shop Including EV",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Fleet Shop Including EV is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Mossy Head Fire Station",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Mossy Head Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027–FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "South End Sub Station",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "South End Sub Station is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Bruce Fire Station",
        "dept": "Sheriff",
        "category": "public safety",
        "category_label": "Public Safety",
        "description": "Bruce Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Boardwalk Dune Walkover Repair/Replacement",
        "dept": "Tourism",
        "category": "tourism",
        "category_label": "Tourism",
        "description": "Boardwalk Dune Walkover Repair/Replacement is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Transit Program Gulfview & Blue Mountain",
        "dept": "Tourism",
        "category": "tourism",
        "category_label": "Tourism",
        "description": "Transit Program Gulfview & Blue Mountain is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Dune Allen Hardscaping Project",
        "dept": "Tourism",
        "category": "tourism",
        "category_label": "Tourism",
        "description": "Dune Allen Hardscaping Project is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$750K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "30A Gateway Improvements",
        "dept": "Tourism",
        "category": "tourism",
        "category_label": "Tourism",
        "description": "30A Gateway Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$600K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pavement Management (PCI)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pavement Management (PCI) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$6.2M",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "US 331 Bridge Lighting",
        "dept": "BCC",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "The proposed project will incorporate bridge lighting across the US 331 Clyde B Wells Bridge in Walton County, FL. This project has been designed by an FDOT Consultant with design funds being allocated through a State legislative appropriation.",
        "budget": "$6M",
        "funding": "Tourist Development Fund",
        "district": "District 5",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "CR 30A & CR 393 Intersection Signalization Improvements",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "CR 30A & CR 393 Intersection Signalization Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$4.4M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Veterans Road Improvements & Extension",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Veterans Road Improvements & Extension is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$4.1M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Driftwood Pointe Rd Sidewalk Phase 4 Final Phase",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Driftwood Pointe Rd Sidewalk Phase 4 Final Phase is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$3.8M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Multi-Use Path - 30A Rebuild 395 to Eastern Lake",
        "dept": "Tourism",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Multi-Use Path - 30A Rebuild 395 to Eastern Lake is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$3.2M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028–FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "CR 393 N Roadway & Pedestrian Improvements Phase 2",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "CR 393 N Roadway & Pedestrian Improvements Phase 2 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2.8M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Mack Bayou/Sandestin Lane Connector Rd",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Mack Bayou/Sandestin Lane Connector Rd is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2.8M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "East Point Washington Roadway & Pedestrian Improvements",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "East Point Washington Roadway & Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$2.7M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "US 98 & South Lakeshore Intersection Signalization Project",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "US 98 & South Lakeshore Intersection Signalization Project is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.8M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028–FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Chat Holley & US 331 Intersection Improvements (Long Term Option)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "This project proposes intersection improvements to include the installation of luminaries on nearby power poles, construction of a southbound right turn lane on US 331, modification of the existing eastbound right turn lane island and radius on Chat Holley Rd, construction of a dedicated...",
        "budget": "$1.8M",
        "funding": "Capital Projects Fund",
        "district": "District 5",
        "target": "FY2027–FY2029",
        "status_text": "Design Phase",
        "status_class": "wc-status-design"
    },
    {
        "title": "Wall Street, Pinewood & Walton Lakeshore Pedestrian Improvements",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Wall Street, Pinewood & Walton Lakeshore Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.7M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "US 331 Multi-Use Path (CR 3280 to North of Bridge)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "US 331 Multi-Use Path (CR 3280 to North of Bridge) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.6M",
        "funding": "Capital Projects Fund",
        "district": "Countywide",
        "target": "FY2028–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "US 98 & Thompson Rd Intersection Signalization Project",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "US 98 & Thompson Rd Intersection Signalization Project is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.5M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028–FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Holiday Rd & CR 2378 (Scenic Gulf Drive) Intersection Improvements",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "The proposed project includes operational improvements to the the CR 2378 (Scenic Gulf Drive) and Holiday Rd intersection, which may include signalization and any other warranted improvements. A signal warrant analysis will be part of the scope of work for this project phase.",
        "budget": "$1.4M",
        "funding": "Capital Projects Fund",
        "district": "District 4",
        "target": "FY2027–FY2030",
        "status_text": "Design Phase",
        "status_class": "wc-status-design"
    },
    {
        "title": "Driftwood & US 98 Intersection Signalization",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "This project includes intersection signalization improvements at US Hwy 98 and Driftwood Rd. Additional intersection improvements that are warranted through the design process will also be included in this project.",
        "budget": "$1.4M",
        "funding": "Capital Projects Fund",
        "district": "District 4",
        "target": "FY2027",
        "status_text": "Construction",
        "status_class": "wc-status-construction"
    },
    {
        "title": "Long Road Bridge Replacement #604130",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Long Road Bridge Replacement #604130 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.4M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028–FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Goldsby Rd Multi-Use Path",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Goldsby Rd Multi-Use Path is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.3M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Huckaba Road #604114 Bridge Replacement",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Huckaba Road #604114 Bridge Replacement is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.1M",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027–FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Whitfield Bridge (#604026) Replacement",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Whitfield Bridge (#604026) Replacement is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1.1M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Multi-use Path - 30A Rebuild 83 to 393",
        "dept": "Tourism",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Multi-use Path - 30A Rebuild 83 to 393 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$1M",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pedestrian Paths_Project 3",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pedestrian Paths_Project 3 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$878K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pedestrian Paths_Project 4",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pedestrian Paths_Project 4 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$878K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Multi-Use Path Bridge Updated Inspection & Recommendation Report",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Multi-Use Path Bridge Updated Inspection & Recommendation Report is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$810K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "CR 83 S Pedestrian Path Extension",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "CR 83 S Pedestrian Path Extension is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$730K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pedestrian Paths_Project 1",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pedestrian Paths_Project 1 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$728K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pedestrian Paths_Project 2",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pedestrian Paths_Project 2 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$728K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "West Hewett Multi-Use Path",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "West Hewett Multi-Use Path is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$585K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Varnum Road #604124 Bridge Replacement",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Varnum Road #604124 Bridge Replacement is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$550K",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pavement Condition Index (PCI) Study",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pavement Condition Index (PCI) Study is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$521K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Deer Lake Path Realignment",
        "dept": "Tourism",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Deer Lake Path Realignment is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$500K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "N Orange Street Pedestrian Improvements",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "N Orange Street Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$449K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Cook Road Reconstruction",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Cook Road Reconstruction is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$442K",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Bridge Design/TBD",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Bridge Design/TBD is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$400K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "E Bay Loop (CR 83A E) Northbound Right Turn Lane",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "The project scope includes the design, permitting and construction of a northbound right turn lane at the East Bay Loop (CR 83A E) and SR 20 intersection in Freeport. In- house design, permitting, surveying and CEI services are included with this project.",
        "budget": "$396K",
        "funding": "Capital Projects Fund",
        "district": "District 1",
        "target": "FY2027",
        "status_text": "Design Phase",
        "status_class": "wc-status-design"
    },
    {
        "title": "Oak Grove Road PH 2 Reconstruction (Resurfacing)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Oak Grove Road PH 2 Reconstruction (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$342K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Intersection Improvements/Turn Lanes (TBD)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Intersection Improvements/Turn Lanes (TBD) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$300K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029–FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Watson Road Paving (Resurfacing)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Watson Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$279K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "CR 30A Sidewalk from Ventana Blvd to Blue Gulf Dr",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "This project includes both the design and construction, in FY 27, for pedestrian improvements along CR 30A from Ventana Blvd to Blue Gulf. Improvements include construction of a sidewalk along the northern portion of CR 30A.",
        "budget": "$230K",
        "funding": "Capital Projects Fund",
        "district": "District 5",
        "target": "FY2027",
        "status_text": "Design Phase",
        "status_class": "wc-status-design"
    },
    {
        "title": "Nancy Darby Road Paving (Resurfacing)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Nancy Darby Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$198K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Seven Oaks Road Paving (Resurfacing)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Seven Oaks Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$154K",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pedestrian Paths_Project 5",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pedestrian Paths_Project 5 is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$150K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2031",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "County Line Road Paving (Resurfacing)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "County Line Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$141K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Joe Dugger Road Paving (Resurfacing)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Joe Dugger Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$138K",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Patch Road (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Patch Road (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$134K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Passion Flower Street (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Passion Flower Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$110K",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Shorey Drive (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Shorey Drive (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$110K",
        "funding": "Transportation Fund",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Arbour Street (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Arbour Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$106K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Rio Ranchero Road (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Rio Ranchero Road (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$105K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Tiger Lily Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Tiger Lily Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$98K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Marigold Avenue (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Marigold Avenue (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$90K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Laurel Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Laurel Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$84K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Clover Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Clover Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$81K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Iris Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Iris Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$80K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Daisy Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Daisy Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$69K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2028",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "ABT Marting (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "ABT Marting (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$60K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Amaryllis Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Amaryllis Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$57K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Honeysuckle Street (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Honeysuckle Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$52K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Pine Tree Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Pine Tree Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$52K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "West Fernwwod Court (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "West Fernwwod Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$51K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "West Violet Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "West Violet Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$44K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2027",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Snapdragon Street (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Snapdragon Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$38K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Cowslip Court (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Cowslip Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$37K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "West Snowdrop Street (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "West Snowdrop Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$35K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Rosewood Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Rosewood Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$32K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Leichen Street (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Leichen Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$28K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Mint Street (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Mint Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$28K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "May Lilly Court (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "May Lilly Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$26K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "SeeSaw Bend (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "SeeSaw Bend (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$21K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Bluebottle Court (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Bluebottle Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$19K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2030",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Red Magnolia Lane (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Red Magnolia Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$18K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    },
    {
        "title": "Walnut Drive (Dirt to Pave)",
        "dept": "Public Works",
        "category": "transportation",
        "category_label": "Transportation",
        "description": "Walnut Drive (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
        "budget": "$15K",
        "funding": "TBD",
        "district": "Countywide",
        "target": "FY2029",
        "status_text": "Planning Phase",
        "status_class": "wc-status-planning"
    }
  ];
