const wcProjects = [
  {
    title: "Baldwin Library/Learning Center",
    slug: "baldwin-library-learning-center",
    proposal_name: "BCC Baldwin Library/Learning Center",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "Baldwin Library/Learning Center is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$8M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Building Construction & Maintenance Facility",
    slug: "building-construction-and-maintenance-facility",
    proposal_name: "BCC Building Construction & Maintenance Facility",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "Building Construction & Maintenance Facility is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$3.5M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Coastal Branch Library Expansion",
    slug: "coastal-branch-library-expansion",
    proposal_name: "BCC Coastal Branch Library Expansion",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "Coastal Branch Library Expansion is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$3M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "US 331 Bridge Lighting",
    slug: "us-331-bridge-lighting",
    proposal_name: "BCC US 331 Bridge Lighting",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "The proposed project will incorporate bridge lighting across the US 331 Clyde B Wells Bridge in Walton County, FL. This project has been designed by an FDOT Consultant with design funds being allocated through a State legislative appropriation.",
    budget: "$6M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "ABT Martin (Dirt to Pave)",
    slug: "abt-martin-dirt-to-pave",
    proposal_name: "PW ABT Martin (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, washboarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$68K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2031",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "Alderberry Connector Road Extension",
    slug: "alderberry-connector-road-extension",
    proposal_name: "PW Alderberry Connector Road Extension",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "This project proposes a new two (2) lane roadway from East Hewett Rd to Don Bishop Rd (via Mario Rd). Project intent it to include Complete Street elements, such as paths, sidewalks, trail or bike lanes.\n\nThis project is part of a phased approach to create an alternative roadway connection to US Hwy 98 and expand the transportation network system in an effort to provide alternate routes, improve safety response time for emergency vehicles, alleviate congested roadways, enhance transportation route redundancy, and improve mobility options in the area.",
    budget: "$8.5M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027–FY2031",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "Amaryllis Lane (Dirt to Pave)",
    slug: "amaryllis-lane-dirt-to-pave",
    proposal_name: "PW Amaryllis Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, wash-boarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$76K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Arbour Street (Dirt to Pave)",
    slug: "arbour-street-dirt-to-pave",
    proposal_name: "PW Arbour Street (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, wash-boarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$107K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Bluebottle Court (Dirt to Pave)",
    slug: "bluebottle-court-dirt-to-pave",
    proposal_name: "PW Bluebottle Court (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, wash-boarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$26K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Blue Gulf Resort Roadway & Drainage Improvements",
    slug: "blue-gulf-resort-roadway-and-drainage-improvements",
    proposal_name: "PW Blue Gulf Resort Roadway & Drainage Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "Blue Gulf Resort Roadway & Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2.5M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Future Bridge Design",
    slug: "future-bridge-design",
    proposal_name: "PW Bridge Design/TBD",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Future Bridge Design is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$400K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Chat Holley & US 331 Intersection Improvements (Long Term Option)",
    slug: "chat-holley-and-us-331-intersection-improvements-long-term-option",
    proposal_name: "PW Chat Holley & US 331 Intersection Improvements (Long Term Option)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "This project proposes intersection improvements to include the installation of luminaries on nearby power poles, construction of a southbound right turn lane on US 331, modification of the existing eastbound right turn lane island and radius on Chat Holley Rd, construction of a dedicated eastbound left turn lane on Chat Holley rd and any other slight realignment to existing southbound travel lanes (south of the intersection) to support the aforementioned intersection modifications.  This project will be constructed within existing County and FDOT right-of-way.",
    budget: "$1.8M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027–FY2029",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "Clover Lane (Dirt to Pave)",
    slug: "clover-lane-dirt-to-pave",
    proposal_name: "PW Clover Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, wash-boarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$112K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Cook Road Reconstruction",
    slug: "cook-road-reconstruction",
    proposal_name: "PW Cook Road Reconstruction",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Cook Road Reconstruction is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$443K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "County Line Road Paving (Resurfacing)",
    slug: "county-line-road-paving-resurfacing",
    proposal_name: "PW County Line Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "County Line Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$141K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Cowslip Court (Dirt to Pave)",
    slug: "cowslip-court-dirt-to-pave",
    proposal_name: "PW Cowslip Court (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, wash-boarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$42K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "CR 280 Bob Sikes Roadway Resurfacing Project Phase I",
    slug: "cr-280-bob-sikes-roadway-resurfacing-project-phase-i",
    proposal_name: "PW CR 280 Bob Sikes Roadway Resurfacing Project Phase I",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "This project scope is for Phase 1 construction of CR 280 Bob Sikes from US 331 to 900 ft west of Pleasant Ridge Rd. Scope of work includes operational improvements such as turn lanes additions and/or expansion near the the US 331 intersection, milling and resurfacing, associated drainage improvements and safety upgrades.",
    budget: "$4.2M",
    funding: "Grant Funded- SCOP",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "CR 30A & CR 393 Intersection Signalization Improvements",
    slug: "cr-30a-and-cr-393-intersection-signalization-improvements",
    proposal_name: "PW CR 30A & CR 393 Intersection Signalization Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "CR 30A & CR 393 Intersection Signalization Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$4.4M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "CR 30A Sidewalk from Ventana Blvd to Blue Gulf Dr",
    slug: "cr-30a-sidewalk-from-ventana-blvd-to-blue-gulf-dr",
    proposal_name: "PW CR 30A Sidewalk from Ventana Blvd to Blue Gulf Dr",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "This project includes both the design and construction, in FY 27, for pedestrian improvements along CR 30A from Ventana Blvd to Blue Gulf.  Improvements include construction of a sidewalk along the northern portion of CR 30A.",
    budget: "$230K",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "CR 30A & S Watersound Parkway Signalized Intersection",
    slug: "cr-30a-and-s-watersound-parkway-signalized-intersection",
    proposal_name: "PW CR 30A & S Watersound Parkway Signalized Intersection",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "CR 30A & S Watersound Parkway Signalized Intersection is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2.5M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "CR 393 N Roadway & Pedestrian Improvements Phase 2",
    slug: "cr-393-n-roadway-and-pedestrian-improvements-phase-2",
    proposal_name: "PW CR 393 N Roadway & Pedestrian Improvements Phase 2",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "CR 393 N Roadway & Pedestrian Improvements Phase 2 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2.8M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "CR 83 N (Blue Mountain Rd) Extension from US 98 to Chat Holley",
    slug: "cr-83-n-blue-mountain-rd-extension-from-us-98-to-chat-holley",
    proposal_name: "PW CR 83 N (Blue Mountain Rd) Extension from US 98 to Chat Holley",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "CR 83 N (Blue Mountain Rd) Extension from US 98 to Chat Holley is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$8.7M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027–FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "CR 83 S Pedestrian Path Extension",
    slug: "cr-83-s-pedestrian-path-extension",
    proposal_name: "PW CR 83 S Pedestrian Path Extension",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "CR 83 S Pedestrian Path Extension is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$730K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Daisy Lane (Dirt to Pave)",
    slug: "daisy-lane-dirt-to-pave",
    proposal_name: "PW Daisy Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Daisy Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$69K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Driftwood Pointe Rd Sidewalk Phase 4 Final Phase",
    slug: "driftwood-pointe-rd-sidewalk-phase-4-final-phase",
    proposal_name: "PW Driftwood Pointe Rd Sidewalk Phase 4 Final Phase",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Driftwood Pointe Rd Sidewalk Phase 4 Final Phase is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$3.8M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Driftwood & US 98 Intersection Signalization",
    slug: "driftwood-and-us-98-intersection-signalization",
    proposal_name: "PW Driftwood & US 98 Intersection Signalization",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "This project includes intersection signalization improvements at US Hwy 98 and Driftwood Rd.  Additional intersection improvements that are warranted through the design process will also be included in this project.",
    budget: "$1.4M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "East Point Washington Roadway & Pedestrian Improvements",
    slug: "east-point-washington-roadway-and-pedestrian-improvements",
    proposal_name: "PW East Point Washington Roadway & Pedestrian Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "East Point Washington Roadway & Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2.7M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "E Bay Loop (CR 83A E) Northbound Right Turn Lane",
    slug: "e-bay-loop-cr-83a-e-northbound-right-turn-lane",
    proposal_name: "PW E Bay Loop (CR 83A E) Northbound Right Turn Lane",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "The project scope includes the design, permitting and construction of a northbound right turn lane at the East Bay Loop (CR 83A E) and SR 20 intersection in Freeport.  In- house design, permitting, surveying and CEI services are included with this project.",
    budget: "$396K",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "Fox Lake Drainage Improvements",
    slug: "fox-lake-drainage-improvements",
    proposal_name: "PW Fox Lake Drainage Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "Fox Lake Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$912K",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Goldsby Rd Multi-Use Path",
    slug: "goldsby-rd-multi-use-path",
    proposal_name: "PW Goldsby Rd Multi-Use Path",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Goldsby Rd Multi-Use Path is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.3M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Hewett Bayou Connector (E Lamb Drive Extension)",
    slug: "hewett-bayou-connector-e-lamb-drive-extension",
    proposal_name: "PW Hewett Bayou Connector (E Lamb Drive Extension)",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "This project is for the construction of a new two (2) lane roadway from East Lamb Drive to East Hewett Rd. Scope of work includes the construction of an approximate 325 ft concrete bridge over Hewett Bayou, attached 6 ft sidewalk and associated drainage features. Roadway segment is one (1) mile in length and will be constructed within existing 66 ft County/Public right-of-way. Mitigation costs for permitting is included in the overall project budget.\n\nThis project is part of a phased approach to create an alternative roadway connection to US Hwy 98 and expand the transportation network system in an effort to provide alternate routes, improve safety response time for emergency vehicles, alleviate congested roadways, enhance transportation route redundancy, and improve mobility options in the area. The project design was previously funded by FDOT's CIGP program. Due to the construction cost as well as for seeking grant funding opportunities, County staff budgeted approximately 50% of the project cost in FY 26 Capital Projects Fund and the remainder of the project cost is requested as part of FY 27 Capital Projects Fund.",
    budget: "$4.6M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "Holiday Rd & CR 2378 (Scenic Gulf Drive) Intersection Improvements",
    slug: "holiday-rd-and-cr-2378-scenic-gulf-drive-intersection-improvements",
    proposal_name: "PW Holiday Rd & CR 2378 (Scenic Gulf Drive) Intersection Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "The proposed project includes operational improvements to the  the CR 2378 (Scenic Gulf Drive) and Holiday Rd intersection, which may include signalization and any other warranted improvements. A signal warrant analysis will be part of the scope of work for this project phase.",
    budget: "$1.4M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027–FY2030",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "Holiday Shores Drainage & Pedestrian Improvements Phase II",
    slug: "holiday-shores-drainage-and-pedestrian-improvements-phase-ii",
    proposal_name: "PW Holiday Shores Drainage & Pedestrian Improvements Phase II",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "The proposed project phase includes the construction of drainage improvements and pedestrian facilities in the Holiday Shores neighborhood area. Phase 2 project limits are Holiday Rd from US Hwy 98 to Forest Shore Drive and east along Forest Shore Drive to Paradise Park.",
    budget: "$7.6M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "Holiday Shores Drainage & Pedestrian Improvements Phase III",
    slug: "holiday-shores-drainage-and-pedestrian-improvements-phase-iii",
    proposal_name: "PW Holiday Shores Drainage & Pedestrian Improvements Phase III",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "Holiday Shores Drainage & Pedestrian Improvements Phase III is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$125K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Honeysuckle Street (Dirt to Pave)",
    slug: "honeysuckle-street-dirt-to-pave",
    proposal_name: "PW Honeysuckle Street (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, wash-boarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$53K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Huckaba Road #604114 Bridge Replacement",
    slug: "huckaba-road-604114-bridge-replacement",
    proposal_name: "PW Huckaba Road #604114 Bridge Replacement",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Huckaba Road #604114 Bridge Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.1M",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027–FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Intersection Improvements/Turn Lanes (TBD)",
    slug: "intersection-improvements-turn-lanes-tbd",
    proposal_name: "PW Intersection Improvements/Turn Lanes (TBD)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Intersection Improvements/Turn Lanes (TBD) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$300K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Iris Lane (Dirt to Pave)",
    slug: "iris-lane-dirt-to-pave",
    proposal_name: "PW Iris Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "The proposed project consists of paving an existing county-maintained dirt roadway to improve the overall safety, reliability, and efficiency of the county’s transportation network. The roadway currently serves local residents, school bus traffic, emergency service providers, and other daily users; however, its unpaved condition creates ongoing maintenance challenges, reduced travel reliability, and hazardous driving conditions during periods of heavy rainfall and dry weather. The project will include roadway grading and shaping, installation or improvement of drainage infrastructure as needed, placement of a stabilized base course, and construction of an asphalt pavement surface. Associated work may also include shoulder improvements, traffic control devices, roadway striping, and erosion control measures necessary to provide a durable and safe transportation corridor. Paving this roadway will provide significant long-term benefits to the county and the traveling public. The project will improve vehicle safety by reducing loose aggregate, washboarding, rutting, dust generation, and muddy conditions that are commonly associated with dirt roads. The improved surface will enhance traction and visibility while reducing the likelihood of accidents and roadway failures during adverse weather conditions. The project will also improve emergency response access and reliability for law enforcement, fire rescue, and medical personnel by providing a dependable all-weather route. School bus operations and daily commuting conditions for residents will be improved through smoother travel surfaces, reduced vehicle wear and tear, and shorter travel times.\n\nFrom an operational standpoint, paving the roadway will reduce the county’s recurring maintenance costs associated with grading, reshaping, dust suppression, and storm-related repairs that are routinely required on unpaved roads. The paved surface will provide a longer-lasting transportation asset that can be maintained more efficiently and economically over time. In addition, the project will support continued growth and economic development within the county by improving connectivity between residential areas, agricultural properties, local businesses, and other public infrastructure. The upgraded roadway will strengthen the county transportation system by providing safer and more dependable access for residents and visitors while enhancing the overall quality of life for the surrounding community.",
    budget: "$110K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Joe Dugger Road Paving (Resurfacing)",
    slug: "joe-dugger-road-paving-resurfacing",
    proposal_name: "PW Joe Dugger Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Joe Dugger Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$138K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Laurel Lane (Dirt to Pave)",
    slug: "laurel-lane-dirt-to-pave",
    proposal_name: "PW Laurel Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Laurel Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$84K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Leichen Street (Dirt to Pave)",
    slug: "leichen-street-dirt-to-pave",
    proposal_name: "PW Leichen Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Leichen Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$28K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Long Road Bridge Replacement #604130",
    slug: "long-road-bridge-replacement-604130",
    proposal_name: "PW Long Road Bridge Replacement #604130",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Long Road Bridge Replacement #604130 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.4M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028–FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Mack Bayou/Sandestin Lane Connector Rd",
    slug: "mack-bayou-sandestin-lane-connector-rd",
    proposal_name: "PW Mack Bayou/Sandestin Lane Connector Rd",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Mack Bayou/Sandestin Lane Connector Rd is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2.8M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Madge Lane & Sally Lane Roadway & Drainage Improvements",
    slug: "madge-lane-and-sally-lane-roadway-and-drainage-improvements",
    proposal_name: "PW Madge Lane & Sally Lane Roadway & Drainage Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "This project includes asphalt paving of existing dirt roads and includes stormwater drainage improvements within existing limited rights-of-way.  No pedestrian features are included with these projects due to the constrained rights-of-way.",
    budget: "$536K",
    funding: "The proposed funding source for the Construction of this project is Public Works Capital (FY 27) with the funding source for CEI is in-house engineering staff. The budgeted amount of $494,000 includes $450,000 for materials only and $54,000 for CEI services (estimated cost if outsourced); however, the CEI services will be performed with in-house engineering staff.",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "Marigold Avenue (Dirt to Pave)",
    slug: "marigold-avenue-dirt-to-pave",
    proposal_name: "PW Marigold Avenue (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Marigold Avenue (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$90K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "May Lilly Court (Dirt to Pave)",
    slug: "may-lilly-court-dirt-to-pave",
    proposal_name: "PW May Lilly Court (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "May Lilly Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$26K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Mint Street (Dirt to Pave)",
    slug: "mint-street-dirt-to-pave",
    proposal_name: "PW Mint Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Mint Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$28K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Morrison Springs Site Improvements (Boat Launch Facility)",
    slug: "morrison-springs-site-improvements-boat-launch-facility",
    proposal_name: "PW Morrison Springs Site Improvements (Boat Launch Facility)",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "Morrison Springs Site Improvements (Boat Launch Facility) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$500K",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Multi-Use Path Bridge Updated Inspection & Recommendation Report",
    slug: "multi-use-path-bridge-updated-inspection-and-recommendation-report",
    proposal_name: "PW Multi-Use Path Bridge Updated Inspection & Recommendation Report",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Multi-Use Path Bridge Updated Inspection & Recommendation Report is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$810K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Nancy Darby Road Paving (Resurfacing)",
    slug: "nancy-darby-road-paving-resurfacing",
    proposal_name: "PW Nancy Darby Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Nancy Darby Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$198K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "N Orange Street Pedestrian Improvements",
    slug: "n-orange-street-pedestrian-improvements",
    proposal_name: "PW N Orange Street Pedestrian Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "N Orange Street Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$449K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Oak Grove Road Phase II (Resurfacing)",
    slug: "oak-grove-road-phase-ii-resurfacing",
    proposal_name: "PW Oak Grove Road PH 2 Reconstruction (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Oak Grove Road Phase II (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$342K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Passion Flower Street (Dirt to Pave)",
    slug: "passion-flower-street-dirt-to-pave",
    proposal_name: "PW Passion Flower Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Passion Flower Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$110K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Patch Road (Dirt to Pave)",
    slug: "patch-road-dirt-to-pave",
    proposal_name: "PW Patch Road (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Patch Road (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$134K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pavement Condition Index (PCI) Study",
    slug: "pavement-condition-index-pci-study",
    proposal_name: "PW Pavement Condition Index (PCI) Study",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pavement Condition Index (PCI) Study is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$521K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pavement Management (PCI) Overlay",
    slug: "pavement-management-pci-overlay",
    proposal_name: "PW Pavement Management (PCI)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pavement Management (PCI) Overlay is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6.2M",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pedestrian Paths_Project 1",
    slug: "pedestrian-paths-project-1",
    proposal_name: "PW Pedestrian Paths_Project 1",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pedestrian Paths_Project 1 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$728K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pedestrian Paths_Project 2",
    slug: "pedestrian-paths-project-2",
    proposal_name: "PW Pedestrian Paths_Project 2",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pedestrian Paths_Project 2 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$728K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pedestrian Paths_Project 3",
    slug: "pedestrian-paths-project-3",
    proposal_name: "PW Pedestrian Paths_Project 3",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pedestrian Paths_Project 3 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$878K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pedestrian Paths_Project 4",
    slug: "pedestrian-paths-project-4",
    proposal_name: "PW Pedestrian Paths_Project 4",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pedestrian Paths_Project 4 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$878K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pedestrian Paths_Project 5",
    slug: "pedestrian-paths-project-5",
    proposal_name: "PW Pedestrian Paths_Project 5",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pedestrian Paths_Project 5 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$150K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pine Tree Lane (Dirt to Pave)",
    slug: "pine-tree-lane-dirt-to-pave",
    proposal_name: "PW Pine Tree Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Pine Tree Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$53K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Poinciana Blvd & Scenic Hwy 98 Intersection Signalization",
    slug: "poinciana-blvd-and-scenic-hwy-98-intersection-signalization",
    proposal_name: "PW Poinciana Blvd & Scenic Hwy 98 Intersection Signalization",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "The intersection signalization of Poinciana Blvd and Scenic Hwy 98 (CR 2378) has been designed. Previously, it was included as part of the Poinciana Blvd Roadway and Drainage Improvements project but recently was determined to separate it in order to expedite the signalization component. Additionally, the Poinciana Blvd Roadway and Drainage Improvements project has been partially funded (pedestrian components) in FY 28 with the Transportation Alternatives program.\n\nProject scope includes signalizing the intersection as well as implementation of pedestrian safety improvements.",
    budget: "$900K",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "Poinicana Blvd Roadway, Drainage & Pedestrian Improvements",
    slug: "poinicana-blvd-roadway-drainage-and-pedestrian-improvements",
    proposal_name: "PW Poinicana Blvd Roadway, Drainage & Pedestrian Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "Poinicana Blvd Roadway, Drainage & Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.8M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Red Magnolia Lane (Dirt to Pave)",
    slug: "red-magnolia-lane-dirt-to-pave",
    proposal_name: "PW Red Magnolia Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Red Magnolia Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$18K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Rio Ranchero Road (Dirt to Pave)",
    slug: "rio-ranchero-road-dirt-to-pave",
    proposal_name: "PW Rio Ranchero Road (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Rio Ranchero Road (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$105K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Rock Hill Rd Improvements - Phase",
    slug: "rock-hill-rd-improvements-phase",
    proposal_name: "PW Rock Hill Rd Improvements - Phase 2",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Rock Hill Rd Improvements - Phase is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2.3M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Rock Hill Rd Improvements - Phase 3",
    slug: "rock-hill-rd-improvements-phase-3",
    proposal_name: "PW Rock Hill Rd Improvements - Phase 3",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Rock Hill Rd Improvements - Phase 3 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$3.2M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Rock Hill Rd Improvements Phase 4 (Final)",
    slug: "rock-hill-rd-improvements-phase-4-final",
    proposal_name: "PW Rock Hill Rd Improvements- Phase 4 (Final)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Rock Hill Rd Improvements Phase 4 (Final) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6.2M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Rosewood Lane (Dirt to Pave)",
    slug: "rosewood-lane-dirt-to-pave",
    proposal_name: "PW Rosewood Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Rosewood Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$32K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "SeeSaw Bend (Dirt to Pave)",
    slug: "seesaw-bend-dirt-to-pave",
    proposal_name: "PW SeeSaw Bend (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "SeeSaw Bend (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$21K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Seven Oaks Road Paving (Resurfacing)",
    slug: "seven-oaks-road-paving-resurfacing",
    proposal_name: "PW Seven Oaks Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Seven Oaks Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$155K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Shorey Drive (Dirt to Pave)",
    slug: "shorey-drive-dirt-to-pave",
    proposal_name: "PW Shorey Drive (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Shorey Drive (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$110K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Snapdragon Street (Dirt to Pave)",
    slug: "snapdragon-street-dirt-to-pave",
    proposal_name: "PW Snapdragon Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Snapdragon Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$39K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "South Orange Street Pedestrian Improvements",
    slug: "south-orange-street-pedestrian-improvements",
    proposal_name: "PW South Orange Street Pedestrian Improvements",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "This project includes the construction of a sidewalk along South Orange Street from US Hwy 98 to Inlet Beach Regional Access Park.",
    budget: "$243K",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "Sugar Drive Connector Rd",
    slug: "sugar-drive-connector-rd",
    proposal_name: "PW Sugar Drive Connector Rd",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "This project proposes a new two (2) lane roadway from Sugar Drive to Thompson Rd. Project intent it to include Complete Street elements, such as paths, sidewalks, trail or bike lanes.",
    budget: "$3.4M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027–FY2030",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "Tiger Lily Lane (Dirt to Pave)",
    slug: "tiger-lily-lane-dirt-to-pave",
    proposal_name: "PW Tiger Lily Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Tiger Lily Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$98K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "US 331 Multi-Use Path (CR 3280 to North of Bridge)",
    slug: "us-331-multi-use-path-cr-3280-to-north-of-bridge",
    proposal_name: "PW US 331 Multi-Use Path (CR 3280 to North of Bridge)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "US 331 Multi-Use Path (CR 3280 to North of Bridge) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.6M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2028–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "US 98 & South Lakeshore Intersection Signalization Project",
    slug: "us-98-and-south-lakeshore-intersection-signalization-project",
    proposal_name: "PW US 98 & South Lakeshore Intersection Signalization Project",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "US 98 & South Lakeshore Intersection Signalization Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.8M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028–FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "US 98 & Thompson Rd Intersection Signalization Project",
    slug: "us-98-and-thompson-rd-intersection-signalization-project",
    proposal_name: "PW US 98 & Thompson Rd Intersection Signalization Project",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "US 98 & Thompson Rd Intersection Signalization Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.5M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028–FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Varnum Road #604124 Bridge Replacement",
    slug: "varnum-road-604124-bridge-replacement",
    proposal_name: "PW Varnum Road #604124 Bridge Replacement",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Varnum Road #604124 Bridge Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$550K",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Veterans Road Improvements & Extension",
    slug: "veterans-road-improvements-and-extension",
    proposal_name: "PW Veterans Road Improvements & Extension",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Veterans Road Improvements & Extension is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$4.1M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2028–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Wall Street, Pinewood and Walton Lakeshore Pedestrian Improvements",
    slug: "wall-street-pinewood-and-walton-lakeshore-pedestrian-improvements",
    proposal_name: "PW Wall Street, Pinewood & Walton Lakeshore Pedestrian Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Wall Street, Pinewood and Walton Lakeshore Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.7M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Walnut Drive (Dirt to Pave)",
    slug: "walnut-drive-dirt-to-pave",
    proposal_name: "PW Walnut Drive (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Walnut Drive (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$15K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Walton Magnolia and Park Place Drainage Improvements",
    slug: "walton-magnolia-and-park-place-drainage-improvements",
    proposal_name: "PW Walton Magnolia and Park Place Drainage Improvements",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "Walton Magnolia and Park Place Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$426K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Watson Road Paving (Resurfacing)",
    slug: "watson-road-paving-resurfacing",
    proposal_name: "PW Watson Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Watson Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$279K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "West Fernwwod Court (Dirt to Pave)",
    slug: "west-fernwwod-court-dirt-to-pave",
    proposal_name: "PW West Fernwwod Court (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "West Fernwwod Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$51K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "West Hewett Multi-Use Path",
    slug: "west-hewett-multi-use-path",
    proposal_name: "PW West Hewett Multi-Use Path",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "West Hewett Multi-Use Path is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$585K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "West Snowdrop Street (Dirt to Pave)",
    slug: "west-snowdrop-street-dirt-to-pave",
    proposal_name: "PW West Snowdrop Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "West Snowdrop Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$35K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "West Violet Lane (Dirt to Pave)",
    slug: "west-violet-lane-dirt-to-pave",
    proposal_name: "PW West Violet Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "West Violet Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$44K",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Whitfield Bridge (#604026) Replacement",
    slug: "whitfield-bridge-604026-replacement",
    proposal_name: "PW Whitfield Bridge (#604026) Replacement",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Whitfield Bridge (#604026) Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1.1M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Bruce Fire Station",
    slug: "bruce-fire-station",
    proposal_name: "Sheriff Bruce Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Bruce Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Fire Station",
    slug: "fire-station",
    proposal_name: "Sheriff Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6.6M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Fleet Shop - including EV",
    slug: "fleet-shop-including-ev",
    proposal_name: "Sheriff Fleet Shop Including EV",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Fleet Shop - including EV is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2030",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Freeport 3280/Bearcreek Fire Station",
    slug: "freeport-3280-bearcreek-fire-station",
    proposal_name: "Sheriff Freeport 3280/Bearcreek Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Freeport 3280/Bearcreek Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$7M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027–FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Hammock Bay Fire Station",
    slug: "hammock-bay-fire-station",
    proposal_name: "Sheriff Hammock Bay Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Hammock Bay Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6.6M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Mossy Head Fire Station",
    slug: "mossy-head-fire-station",
    proposal_name: "Sheriff Mossy Head Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Mossy Head Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6M",
    funding: "Grant Funded",
    district: "Countywide",
    target: "FY2027–FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Pleasant Ridge Fire Station",
    slug: "pleasant-ridge-fire-station",
    proposal_name: "Sheriff Pleasant Ridge Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Pleasant Ridge Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$7M",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027–FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Triumph Radio Project",
    slug: "sheriff-triumph-radio-project",
    proposal_name: "Sheriff Radio Project",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Triumph Radio Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$10.1M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "South End Sub Station",
    slug: "south-end-sub-station",
    proposal_name: "Sheriff South End Sub Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "South End Sub Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$5M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2029–FY2031",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "30A Gateway Improvements",
    slug: "30a-gateway-improvements",
    proposal_name: "TDT 30A Gateway Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "30A Gateway Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$600K",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Boardwalk Dune Walkover Repair/Replacement",
    slug: "boardwalk-dune-walkover-repair-replacement",
    proposal_name: "TDT Boardwalk Dune Walkover Repair/Replacement",
    dept: "Walton County",
    category: "tourism",
    category_label: "Tourism",
    description: "Boardwalk Dune Walkover Repair/Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Deer Lake Path Realignment",
    slug: "deer-lake-path-realignment",
    proposal_name: "TDT Deer Lake Path Realignment",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Deer Lake Path Realignment is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$500K",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Dune Allen Hardscaping Project",
    slug: "dune-allen-hardscaping-project",
    proposal_name: "TDT Dune Allen Hardscaping Project",
    dept: "Walton County",
    category: "tourism",
    category_label: "Tourism",
    description: "Dune Allen Hardscaping Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$750K",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Miramar Beach Parking Facility",
    slug: "miramar-beach-parking-facility",
    proposal_name: "TDT Miramar Beach Parking Facility",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "Miramar Beach Parking Facility is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6.5M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Multi-use Path - 30A Rebuild 395 to Eastern Lake",
    slug: "multi-use-path-30a-rebuild-395-to-eastern-lake",
    proposal_name: "TDT Multi-Use Path - 30A Rebuild 395 to Eastern Lake",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Multi-use Path - 30A Rebuild 395 to Eastern Lake is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$3.3M",
    funding: "TBD",
    district: "Countywide",
    target: "FY2028–FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Multi-use Path - 30A Rebuild 83 to 393",
    slug: "multi-use-path-30a-rebuild-83-to-393",
    proposal_name: "TDT Multi-use Path - 30A Rebuild 83 to 393",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Multi-use Path - 30A Rebuild 83 to 393 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Santa Rosa Beach Performing Arts Park",
    slug: "santa-rosa-beach-performing-arts-park",
    proposal_name: "TDT Santa Rosa Beach Performing Arts Park",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "Santa Rosa Beach Performing Arts Park is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$6.5M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Visitor and Discovery Center",
    slug: "visitor-and-discovery-center",
    proposal_name: "TDT Tourism Visitor and Discovery Center",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "Visitor and Discovery Center is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$9.5M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2029",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Transit Program Gulfview & Blue Mountain",
    slug: "transit-program-gulfview-and-blue-mountain",
    proposal_name: "TDT Transit Program Gulfview & Blue Mountain",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "Transit Program Gulfview & Blue Mountain is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$1M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Walton Dunes Beach Access",
    slug: "walton-dunes-beach-access",
    proposal_name: "TDT Walton Dunes Beach Access",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "Walton Dunes Beach Access is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$2.1M",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2028",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  }
];
