const wcProjects = [
  {
    title: "BCC Baldwin Library/Learning Center",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "BCC Baldwin Library/Learning Center is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "BCC Building Construction & Maintenance Facility",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "BCC Building Construction & Maintenance Facility is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "BCC Coastal Branch Library Expansion",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "BCC Coastal Branch Library Expansion is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "BCC US 331 Bridge Lighting",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "BCC US 331 Bridge Lighting is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Per the latest from FDOT, Total Project Cost is approximately $8,807,000 with the following breakdown:\n\n$606,466 (Remaining Design Funds from Legislative Appropriation No. 1)\n$2,900,000 ( Legislative Appropriation No.2- Per FDOT)\n$2,900, 000 (Legislative Appropriation No.2 Local Match Requirement- Per FDOT)\n\nUnfunded Need= Approximately $2,400,000\n\nTotal County Contribution = $2.9 M + $2.4 M = $5.3 M",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW ABT Marting (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW ABT Marting (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Alderberry Connector Road Extension",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Alderberry Connector Road Extension is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Design phase (FY 27) will be with in-house engineering staff. The budgeted amount of $600,000 would be the anticipated cost for outsourcing of the project.\n\nThe proposed funding source for the Construction phase (FY 31) has yet to be determined but staff will continue to evaluate any applicable and appropriate grant sources that may be available to either partially or fully fund this project.",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "PW Amaryllis Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Amaryllis Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Arbour Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Arbour Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Bluebottle Court (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Bluebottle Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Blue Gulf Resort Roadway & Drainage Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "PW Blue Gulf Resort Roadway & Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Bridge Design/TBD",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Bridge Design/TBD is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Chat Holley & US 331 Intersection Improvements (Long Term Option)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Chat Holley & US 331 Intersection Improvements (Long Term Option) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Design phase (FY 27) will be the Capital Projects Fund.  Engineering staff did submit a CIGP application to the Florida Department of Transportation for consideration for financial assistance for this project in March 2026.  FDOT does not typically announce their draft Five Year Work Plan, which would include grant funded projects, until November/December of each year.  It should be noted that the CIGP grant does require a match from the County.  Therefore, in the event of grant award, the County would still have to provide matching funds for the project. \n\nThe proposed funding source for the Construction phase (FY 29) has yet to be determined but staff will continue to evaluate any applicable and appropriate grant sources that may be available to either partially or fully fund this project.",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "PW Clover Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Clover Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Cook Road Reconstruction",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Cook Road Reconstruction is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW County Line Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW County Line Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Cowslip Court (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Cowslip Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW CR 280 Bob Sikes Roadway Resurfacing Project Phase I",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW CR 280 Bob Sikes Roadway Resurfacing Project Phase I is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Grant Funded- SCOP",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW CR 30A & CR 393 Intersection Signalization Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW CR 30A & CR 393 Intersection Signalization Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW CR 30A Sidewalk from Ventana Blvd to Blue Gulf Dr",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW CR 30A Sidewalk from Ventana Blvd to Blue Gulf Dr is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Design phase (FY 27) will be with in-house engineering staff. The budgeted amount of $34,800 would be the anticipated cost for outsourcing of the project.\n\nThe proposed funding source for Construction will be Capital Projects Fund, material only cost.  Public Works in-house crews will be utilized for construction activities and in-house engineering staff will provide CEI services.  The budgeted amount of $20,880 would be the anticipated cost for outsourcing of the project.\n\nTotal project cost of $229,680 with a breakdown as follows:\n • Design Cost: $34,800 (anticipated cost for outsourcing of the project; will be done with in-house engineering staff)\n • Construction Cost (Materials Only): $174,000\n • CEI Cost: $20,8800 (anticipated cost for outsourcing of the project; will be done with in-house engineering staff)",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "PW CR 30A & S Watersound Parkway Signalized Intersection",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "PW CR 30A & S Watersound Parkway Signalized Intersection is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW CR 393 N Roadway & Pedestrian Improvements Phase 2",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW CR 393 N Roadway & Pedestrian Improvements Phase 2 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW CR 83 N (Blue Mountain Rd) Extension from US 98 to Chat Holley",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW CR 83 N (Blue Mountain Rd) Extension from US 98 to Chat Holley is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW CR 83 S Pedestrian Path Extension",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW CR 83 S Pedestrian Path Extension is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Daisy Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Daisy Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Driftwood Pointe Rd Sidewalk Phase 4 Final Phase",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Driftwood Pointe Rd Sidewalk Phase 4 Final Phase is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Driftwood & US 98 Intersection Signalization",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Driftwood & US 98 Intersection Signalization is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "This project is funded by various funding sources: \n • \t$750,000 previously encumbered from Proportional Fair Share (PFS) funds; $125,000 of those funds were utilized for design and permitting services leaving the remainder of $625,000 for construction activities\n •     $250,000 from remaining FY 26 Capital Project Funds (based on current projects coming in under the budgeted amount)\n •     $525,000 from FY 27 Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW East Point Washington Roadway & Pedestrian Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW East Point Washington Roadway & Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW E Bay Loop (CR 83A E) Northbound Right Turn Lane",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW E Bay Loop (CR 83A E) Northbound Right Turn Lane is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "County staff has had preliminary discussions with City of Freeport staff on the project need.  Potential partnering of the project may be feasible.",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "PW Fox Lake Drainage Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "PW Fox Lake Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Goldsby Rd Multi-Use Path",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Goldsby Rd Multi-Use Path is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Hewett Bayou Connector (E Lamb Drive Extension)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Hewett Bayou Connector (E Lamb Drive Extension) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Construction phase was split into two years (FY 26 and FY 27).\n • The amount funded from the FY 26 Capital Projects Fund was $4,271,415.\n • The amount requested from the FY 27 Capital Projects Fund is $4,571,536.\n\nApplications for grant assistance have been submitted to FDOT over multiple years/cycles but was not funded. Previously, the design was funded by FDOT. Due to the timeframe/expiration of the project permits (State and Federal), this project is recommended to move forward with funds programmed by the Capital projects Fund.",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW Holiday Rd & CR 2378 (Scenic Gulf Drive) Intersection Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Holiday Rd & CR 2378 (Scenic Gulf Drive) Intersection Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Design phase (FY 27) will be the Capital Projects Fund.\n \nThe proposed funding source for the Construction phase (FY 30) has yet to be determined but staff will continue to evaluate any applicable and appropriate grant or other funding sources that may be available to either partially or fully fund this project.",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "PW Holiday Shores Drainage & Pedestrian Improvements Phase II",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "PW Holiday Shores Drainage & Pedestrian Improvements Phase II is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Construction phase (FY 27) will be Capital Projects Fund with  CEI services provided by in-house engineering staff. The budgeted amount of $7,560,000 would be broken down as follows:\n\n • Construction Costs: $7,000,000 (Out-sourced)\n • CEI Costs: $560,000  (anticipated cost for outsourcing of the project; will be done with in-house engineering staff)",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW Holiday Shores Drainage & Pedestrian Improvements Phase III",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "PW Holiday Shores Drainage & Pedestrian Improvements Phase III is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Honeysuckle Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Honeysuckle Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Huckaba Road #604114 Bridge Replacement",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Huckaba Road #604114 Bridge Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Intersection Improvements/Turn Lanes (TBD)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Intersection Improvements/Turn Lanes (TBD) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Iris Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Iris Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Joe Dugger Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Joe Dugger Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Laurel Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Laurel Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Leichen Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Leichen Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Long Road Bridge Replacement #604130",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Long Road Bridge Replacement #604130 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Mack Bayou/Sandestin Lane Connector Rd",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Mack Bayou/Sandestin Lane Connector Rd is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Madge Lane & Sally Lane Roadway & Drainage Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "PW Madge Lane & Sally Lane Roadway & Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Construction of this project is Public Works Capital (FY 27) with the funding source for CEI is in-house engineering staff. The budgeted amount of $494,000 includes $450,000 for materials only and $54,000 for CEI services (estimated cost if outsourced); however, the CEI services will be performed with in-house engineering staff.",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW Marigold Avenue (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Marigold Avenue (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW May Lilly Court (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW May Lilly Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Mint Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Mint Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Morrison Springs Site Improvements (Boat Launch Facility)",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "PW Morrison Springs Site Improvements (Boat Launch Facility) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Multi-Use Path Bridge Updated Inspection & Recommendation Report",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Multi-Use Path Bridge Updated Inspection & Recommendation Report is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Nancy Darby Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Nancy Darby Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW N Orange Street Pedestrian Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW N Orange Street Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Oak Grove Road PH 2 Reconstruction (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Oak Grove Road PH 2 Reconstruction (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Passion Flower Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Passion Flower Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Patch Road (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Patch Road (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pavement Condition Index (PCI) Study",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pavement Condition Index (PCI) Study is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pavement Management (PCI)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pavement Management (PCI) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pedestrian Paths_Project 1",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pedestrian Paths_Project 1 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pedestrian Paths_Project 2",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pedestrian Paths_Project 2 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pedestrian Paths_Project 3",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pedestrian Paths_Project 3 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pedestrian Paths_Project 4",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pedestrian Paths_Project 4 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pedestrian Paths_Project 5",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pedestrian Paths_Project 5 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Pine Tree Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Pine Tree Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Poinciana Blvd & Scenic Hwy 98 Intersection Signalization",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Poinciana Blvd & Scenic Hwy 98 Intersection Signalization is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW Poinicana Blvd Roadway, Drainage & Pedestrian Improvements",
    dept: "Walton County",
    category: "drainage",
    category_label: "Drainage",
    description: "PW Poinicana Blvd Roadway, Drainage & Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Red Magnolia Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Red Magnolia Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Rio Ranchero Road (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Rio Ranchero Road (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Rock Hill Rd Improvements - Phase 2",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Rock Hill Rd Improvements - Phase 2 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Rock Hill Rd Improvements - Phase 3",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Rock Hill Rd Improvements - Phase 3 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Rock Hill Rd Improvements- Phase 4 (Final)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Rock Hill Rd Improvements- Phase 4 (Final) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Rosewood Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Rosewood Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW SeeSaw Bend (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW SeeSaw Bend (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Seven Oaks Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Seven Oaks Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Shorey Drive (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Shorey Drive (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Snapdragon Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Snapdragon Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW South Orange Street Pedestrian Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW South Orange Street Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Construction phase (FY 27) will be Capital Projects Fund.  Construction activities will be performed by Public Works in-house crews and CEI will be performed with in-house engineering staff. The budgeted amount of $243,200 is total project cost with a breakdown as follows:\n • $200,000 (for construction materials only)\n • $43,200  ( anticipated cost for outsourcing of the project; to be performed by in-house engineering staff)",
    district: "Countywide",
    target: "FY2027",
    status_text: "Construction",
    status_class: "wc-status-construction"
  },
  {
    title: "PW Sugar Drive Connector Rd",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Sugar Drive Connector Rd is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "The proposed funding source for the Design phase (FY 27) will be with in-house engineering staff. The budgeted amount of $300,000 would be the anticipated cost for outsourcing of the project.\n\nRight of way acquisition will be a part of this project and is currently anticipated at approximately $600,000.\n\nThe proposed funding source for the Construction phase (FY 30) has yet to be determined but staff will continue to evaluate any applicable and appropriate grant sources that may be available to either partially or fully fund this project. \n\nTotal project cost breakdown is estimated at $3,400,000 with a breakdown as follows:\n • ROW Acquisition Costs: $600,000\n • Design Costs: $300,000 (anticipated cost for outsourcing of the project; will be performed by in-house engineering staff)\n • Construction/CEI: $2,500,000",
    district: "Countywide",
    target: "FY2027",
    status_text: "Design Phase",
    status_class: "wc-status-design"
  },
  {
    title: "PW Tiger Lily Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Tiger Lily Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW US 331 Multi-Use Path (CR 3280 to North of Bridge)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW US 331 Multi-Use Path (CR 3280 to North of Bridge) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW US 98 & South Lakeshore Intersection Signalization Project",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW US 98 & South Lakeshore Intersection Signalization Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW US 98 & Thompson Rd Intersection Signalization Project",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW US 98 & Thompson Rd Intersection Signalization Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Varnum Road #604124 Bridge Replacement",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Varnum Road #604124 Bridge Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Transportation Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Veterans Road Improvements & Extension",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Veterans Road Improvements & Extension is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Wall Street, Pinewood & Walton Lakeshore Pedestrian Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Wall Street, Pinewood & Walton Lakeshore Pedestrian Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Walnut Drive (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Walnut Drive (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Walton Magnolia and Park Place Drainage Improvements",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "PW Walton Magnolia and Park Place Drainage Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Watson Road Paving (Resurfacing)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Watson Road Paving (Resurfacing) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW West Fernwwod Court (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW West Fernwwod Court (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW West Hewett Multi-Use Path",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW West Hewett Multi-Use Path is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW West Snowdrop Street (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW West Snowdrop Street (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW West Violet Lane (Dirt to Pave)",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW West Violet Lane (Dirt to Pave) is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "PW Whitfield Bridge (#604026) Replacement",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "PW Whitfield Bridge (#604026) Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Bruce Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Bruce Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Fleet Shop Including EV",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Fleet Shop Including EV is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Freeport 3280/Bearcreek Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Freeport 3280/Bearcreek Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Hammock Bay Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Hammock Bay Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Mossy Head Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Mossy Head Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Grant Funded",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Pleasant Ridge Fire Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Pleasant Ridge Fire Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Capital Projects Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff Radio Project",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff Radio Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "Sheriff South End Sub Station",
    dept: "Walton County",
    category: "public safety",
    category_label: "Public Safety",
    description: "Sheriff South End Sub Station is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT 30A Gateway Improvements",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "TDT 30A Gateway Improvements is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Boardwalk Dune Walkover Repair/Replacement",
    dept: "Walton County",
    category: "tourism",
    category_label: "Tourism",
    description: "TDT Boardwalk Dune Walkover Repair/Replacement is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Deer Lake Path Realignment",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "TDT Deer Lake Path Realignment is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Dune Allen Hardscaping Project",
    dept: "Walton County",
    category: "tourism",
    category_label: "Tourism",
    description: "TDT Dune Allen Hardscaping Project is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Miramar Beach Parking Facility",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "TDT Miramar Beach Parking Facility is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Multi-Use Path - 30A Rebuild 395 to Eastern Lake",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "TDT Multi-Use Path - 30A Rebuild 395 to Eastern Lake is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "TBD",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Multi-use Path - 30A Rebuild 83 to 393",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "TDT Multi-use Path - 30A Rebuild 83 to 393 is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Santa Rosa Beach Performing Arts Park",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "TDT Santa Rosa Beach Performing Arts Park is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Tourism Visitor and Discovery Center",
    dept: "Walton County",
    category: "facilities",
    category_label: "Facilities",
    description: "TDT Tourism Visitor and Discovery Center is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Transit Program Gulfview & Blue Mountain",
    dept: "Walton County",
    category: "transportation",
    category_label: "Transportation",
    description: "TDT Transit Program Gulfview & Blue Mountain is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  },
  {
    title: "TDT Walton Dunes Beach Access",
    dept: "Walton County",
    category: "parks",
    category_label: "Parks",
    description: "TDT Walton Dunes Beach Access is included in Walton County’s five-year Capital Improvement Plan.",
    budget: "$0",
    funding: "Tourist Development Fund",
    district: "Countywide",
    target: "FY2027",
    status_text: "Planning Phase",
    status_class: "wc-status-planning"
  }
];
